apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world-2
    name: hello-world-2
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world-2
    name: hello-world-2
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hello-world-2:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: network-test/
      git:
        uri: https://github.com/gowdhaman-j/rhos-certification-prep.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: i7uAjwZ2A1GTRmto40G-
      type: GitHub
    - generic:
        secret: UmEx4eCss-PUIg0oIMg0
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world-2
    name: hello-world-2
  spec:
    replicas: 1
    selector:
      app: hello-world-2
      deploymentconfig: hello-world-2
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: hello-world-2
          deploymentconfig: hello-world-2
      spec:
        containers:
        - image: hello-world-2:latest
          name: hello-world-2
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          readinessProbe:
          initialDelaySeconds: 30
          failureThreshold: 4
          httpGet:
            path: /
            port: 8080
          livenessProbe: 
          initialDelaySeconds: 60
          periodSeconds: 5
          exec: 
            command: ["ls","/index.php"]
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hello-world-2
        from:
          kind: ImageStreamTag
          name: hello-world-2:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-world-2
    name: hello-world-2
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: hello-world-2
      deploymentconfig: hello-world-2
  status:
    loadBalancer: {}
kind: List
metadata: {}
